apiVersion: v1
kind: PersistentVolume
metadata:
  name: test12-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfsshare/test12
    server: 192.168.0.75 
